import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { css } from "@emotion/css";
import { Button } from "../components/Button";
import { Button as Buton } from "@mui/material";
import { useRouter } from "next/router";
import Link from "next/link";
const Home: NextPage = () => {
  const router = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Project Review</a>
        </h1>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
            <Button text="Docs" varient="primary" />
          </a>

          <div className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
            <Buton
              style={{ alignSelf: "flex-end" }}
              variant="contained"
              onClick={() => {
                console.log("clicked");
                router.push("/page2");
              }}
            >
              Learn
            </Buton>
          </div>

          <div className={styles.card}>
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
            <Button text="Examples" varient="danger" />
          </div>

          <div
            style={{
              display: "flex",
              flexDirection: "column",
              margin: "1rem",
              padding: "1.5rem",
              textAlign: "left",
              color: "inherit",
              textDecoration: "none",
              border: "1px solid #222",
              borderRadius: "10px",
              transition: "color 0.15s ease, border-color 0.15s ease",
              maxWidth: "300px",
            }}
          >
            <h2>Core App &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
            <Link href={"/core"}>
              <Buton
                variant="contained"
                style={{ alignSelf: "flex-end" }}
                className={css({
                  marginTop: 60,
                  fontWeight: "bold",
                  width: 150,
                })}
              >
                Go to Core App
              </Buton>
            </Link>
          </div>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
